#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="the_ecs")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttb_control(tb_control instance);
  partial void Updatetb_control(tb_control instance);
  partial void Deletetb_control(tb_control instance);
  partial void Inserttb_event(tb_event instance);
  partial void Updatetb_event(tb_event instance);
  partial void Deletetb_event(tb_event instance);
  partial void Inserttb_season(tb_season instance);
  partial void Updatetb_season(tb_season instance);
  partial void Deletetb_season(tb_season instance);
  partial void Inserttb_user(tb_user instance);
  partial void Updatetb_user(tb_user instance);
  partial void Deletetb_user(tb_user instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["the_ecsConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tb_control> tb_controls
	{
		get
		{
			return this.GetTable<tb_control>();
		}
	}
	
	public System.Data.Linq.Table<tb_event> tb_events
	{
		get
		{
			return this.GetTable<tb_event>();
		}
	}
	
	public System.Data.Linq.Table<tb_season> tb_seasons
	{
		get
		{
			return this.GetTable<tb_season>();
		}
	}
	
	public System.Data.Linq.Table<tb_user> tb_users
	{
		get
		{
			return this.GetTable<tb_user>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_control")]
public partial class tb_control : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private System.Nullable<int> _event_id;
	
	private System.Nullable<int> _user_id;
	
	private System.Nullable<System.DateTime> _entrada;
	
	private System.Nullable<System.DateTime> _saida;
	
	private string _horas;
	
	private System.Nullable<int> _checkin;
	
	private System.Nullable<System.DateTime> _horasLiberado;
	
	private System.Nullable<System.TimeSpan> _horasTotal;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onevent_idChanging(System.Nullable<int> value);
    partial void Onevent_idChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    partial void OnentradaChanging(System.Nullable<System.DateTime> value);
    partial void OnentradaChanged();
    partial void OnsaidaChanging(System.Nullable<System.DateTime> value);
    partial void OnsaidaChanged();
    partial void OnhorasChanging(string value);
    partial void OnhorasChanged();
    partial void OncheckinChanging(System.Nullable<int> value);
    partial void OncheckinChanged();
    partial void OnhorasLiberadoChanging(System.Nullable<System.DateTime> value);
    partial void OnhorasLiberadoChanged();
    partial void OnhorasTotalChanging(System.Nullable<System.TimeSpan> value);
    partial void OnhorasTotalChanged();
    #endregion
	
	public tb_control()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_id", DbType="Int")]
	public System.Nullable<int> event_id
	{
		get
		{
			return this._event_id;
		}
		set
		{
			if ((this._event_id != value))
			{
				this.Onevent_idChanging(value);
				this.SendPropertyChanging();
				this._event_id = value;
				this.SendPropertyChanged("event_id");
				this.Onevent_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
	public System.Nullable<int> user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entrada", DbType="DateTime")]
	public System.Nullable<System.DateTime> entrada
	{
		get
		{
			return this._entrada;
		}
		set
		{
			if ((this._entrada != value))
			{
				this.OnentradaChanging(value);
				this.SendPropertyChanging();
				this._entrada = value;
				this.SendPropertyChanged("entrada");
				this.OnentradaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saida", DbType="DateTime")]
	public System.Nullable<System.DateTime> saida
	{
		get
		{
			return this._saida;
		}
		set
		{
			if ((this._saida != value))
			{
				this.OnsaidaChanging(value);
				this.SendPropertyChanging();
				this._saida = value;
				this.SendPropertyChanged("saida");
				this.OnsaidaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_horas", DbType="VarChar(50)")]
	public string horas
	{
		get
		{
			return this._horas;
		}
		set
		{
			if ((this._horas != value))
			{
				this.OnhorasChanging(value);
				this.SendPropertyChanging();
				this._horas = value;
				this.SendPropertyChanged("horas");
				this.OnhorasChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkin", DbType="Int")]
	public System.Nullable<int> checkin
	{
		get
		{
			return this._checkin;
		}
		set
		{
			if ((this._checkin != value))
			{
				this.OncheckinChanging(value);
				this.SendPropertyChanging();
				this._checkin = value;
				this.SendPropertyChanged("checkin");
				this.OncheckinChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_horasLiberado", DbType="DateTime")]
	public System.Nullable<System.DateTime> horasLiberado
	{
		get
		{
			return this._horasLiberado;
		}
		set
		{
			if ((this._horasLiberado != value))
			{
				this.OnhorasLiberadoChanging(value);
				this.SendPropertyChanging();
				this._horasLiberado = value;
				this.SendPropertyChanged("horasLiberado");
				this.OnhorasLiberadoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_horasTotal", DbType="Time")]
	public System.Nullable<System.TimeSpan> horasTotal
	{
		get
		{
			return this._horasTotal;
		}
		set
		{
			if ((this._horasTotal != value))
			{
				this.OnhorasTotalChanging(value);
				this.SendPropertyChanging();
				this._horasTotal = value;
				this.SendPropertyChanged("horasTotal");
				this.OnhorasTotalChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_event")]
public partial class tb_event : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _nome;
	
	private System.Nullable<System.DateTime> _date;
	
	private System.Nullable<System.TimeSpan> _time;
	
	private System.Nullable<byte> _event_check;
	
	private string _event_time;
	
	private System.Nullable<int> _season_id;
	
	private System.Nullable<int> _duracao;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OntimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OntimeChanged();
    partial void Onevent_checkChanging(System.Nullable<byte> value);
    partial void Onevent_checkChanged();
    partial void Onevent_timeChanging(string value);
    partial void Onevent_timeChanged();
    partial void Onseason_idChanging(System.Nullable<int> value);
    partial void Onseason_idChanged();
    partial void OnduracaoChanging(System.Nullable<int> value);
    partial void OnduracaoChanged();
    #endregion
	
	public tb_event()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(50)")]
	public string nome
	{
		get
		{
			return this._nome;
		}
		set
		{
			if ((this._nome != value))
			{
				this.OnnomeChanging(value);
				this.SendPropertyChanging();
				this._nome = value;
				this.SendPropertyChanged("nome");
				this.OnnomeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date")]
	public System.Nullable<System.DateTime> date
	{
		get
		{
			return this._date;
		}
		set
		{
			if ((this._date != value))
			{
				this.OndateChanging(value);
				this.SendPropertyChanging();
				this._date = value;
				this.SendPropertyChanged("date");
				this.OndateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="Time")]
	public System.Nullable<System.TimeSpan> time
	{
		get
		{
			return this._time;
		}
		set
		{
			if ((this._time != value))
			{
				this.OntimeChanging(value);
				this.SendPropertyChanging();
				this._time = value;
				this.SendPropertyChanged("time");
				this.OntimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_check", DbType="TinyInt")]
	public System.Nullable<byte> event_check
	{
		get
		{
			return this._event_check;
		}
		set
		{
			if ((this._event_check != value))
			{
				this.Onevent_checkChanging(value);
				this.SendPropertyChanging();
				this._event_check = value;
				this.SendPropertyChanged("event_check");
				this.Onevent_checkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_time", DbType="VarChar(50)")]
	public string event_time
	{
		get
		{
			return this._event_time;
		}
		set
		{
			if ((this._event_time != value))
			{
				this.Onevent_timeChanging(value);
				this.SendPropertyChanging();
				this._event_time = value;
				this.SendPropertyChanged("event_time");
				this.Onevent_timeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_season_id", DbType="Int")]
	public System.Nullable<int> season_id
	{
		get
		{
			return this._season_id;
		}
		set
		{
			if ((this._season_id != value))
			{
				this.Onseason_idChanging(value);
				this.SendPropertyChanging();
				this._season_id = value;
				this.SendPropertyChanged("season_id");
				this.Onseason_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duracao", DbType="Int")]
	public System.Nullable<int> duracao
	{
		get
		{
			return this._duracao;
		}
		set
		{
			if ((this._duracao != value))
			{
				this.OnduracaoChanging(value);
				this.SendPropertyChanging();
				this._duracao = value;
				this.SendPropertyChanged("duracao");
				this.OnduracaoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_season")]
public partial class tb_season : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Nome;
	
	private string _Data;
	
	private string _Certificado;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnDataChanging(string value);
    partial void OnDataChanged();
    partial void OnCertificadoChanging(string value);
    partial void OnCertificadoChanged();
    #endregion
	
	public tb_season()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50)")]
	public string Nome
	{
		get
		{
			return this._Nome;
		}
		set
		{
			if ((this._Nome != value))
			{
				this.OnNomeChanging(value);
				this.SendPropertyChanging();
				this._Nome = value;
				this.SendPropertyChanged("Nome");
				this.OnNomeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="VarChar(50)")]
	public string Data
	{
		get
		{
			return this._Data;
		}
		set
		{
			if ((this._Data != value))
			{
				this.OnDataChanging(value);
				this.SendPropertyChanging();
				this._Data = value;
				this.SendPropertyChanged("Data");
				this.OnDataChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Certificado", DbType="VarChar(15)")]
	public string Certificado
	{
		get
		{
			return this._Certificado;
		}
		set
		{
			if ((this._Certificado != value))
			{
				this.OnCertificadoChanging(value);
				this.SendPropertyChanging();
				this._Certificado = value;
				this.SendPropertyChanged("Certificado");
				this.OnCertificadoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_users")]
public partial class tb_user : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _nome;
	
	private string _rg;
	
	private string _telefone;
	
	private string _celular;
	
	private string _curso;
	
	private string _email;
	
	private string _ensino;
	
	private System.Nullable<int> _periodo;
	
	private System.Nullable<byte> _membro;
	
	private System.Nullable<byte> _pagamento;
	
	private System.Nullable<int> _season_id;
	
	private string _horas_total;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnrgChanging(string value);
    partial void OnrgChanged();
    partial void OntelefoneChanging(string value);
    partial void OntelefoneChanged();
    partial void OncelularChanging(string value);
    partial void OncelularChanged();
    partial void OncursoChanging(string value);
    partial void OncursoChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnensinoChanging(string value);
    partial void OnensinoChanged();
    partial void OnperiodoChanging(System.Nullable<int> value);
    partial void OnperiodoChanged();
    partial void OnmembroChanging(System.Nullable<byte> value);
    partial void OnmembroChanged();
    partial void OnpagamentoChanging(System.Nullable<byte> value);
    partial void OnpagamentoChanged();
    partial void Onseason_idChanging(System.Nullable<int> value);
    partial void Onseason_idChanged();
    partial void Onhoras_totalChanging(string value);
    partial void Onhoras_totalChanged();
    #endregion
	
	public tb_user()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(50)")]
	public string nome
	{
		get
		{
			return this._nome;
		}
		set
		{
			if ((this._nome != value))
			{
				this.OnnomeChanging(value);
				this.SendPropertyChanging();
				this._nome = value;
				this.SendPropertyChanged("nome");
				this.OnnomeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rg", DbType="Char(10)")]
	public string rg
	{
		get
		{
			return this._rg;
		}
		set
		{
			if ((this._rg != value))
			{
				this.OnrgChanging(value);
				this.SendPropertyChanging();
				this._rg = value;
				this.SendPropertyChanged("rg");
				this.OnrgChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefone", DbType="Char(10)")]
	public string telefone
	{
		get
		{
			return this._telefone;
		}
		set
		{
			if ((this._telefone != value))
			{
				this.OntelefoneChanging(value);
				this.SendPropertyChanging();
				this._telefone = value;
				this.SendPropertyChanged("telefone");
				this.OntelefoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="Char(11)")]
	public string celular
	{
		get
		{
			return this._celular;
		}
		set
		{
			if ((this._celular != value))
			{
				this.OncelularChanging(value);
				this.SendPropertyChanging();
				this._celular = value;
				this.SendPropertyChanged("celular");
				this.OncelularChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curso", DbType="VarChar(45)")]
	public string curso
	{
		get
		{
			return this._curso;
		}
		set
		{
			if ((this._curso != value))
			{
				this.OncursoChanging(value);
				this.SendPropertyChanging();
				this._curso = value;
				this.SendPropertyChanged("curso");
				this.OncursoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ensino", DbType="VarChar(45)")]
	public string ensino
	{
		get
		{
			return this._ensino;
		}
		set
		{
			if ((this._ensino != value))
			{
				this.OnensinoChanging(value);
				this.SendPropertyChanging();
				this._ensino = value;
				this.SendPropertyChanged("ensino");
				this.OnensinoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_periodo", DbType="Int")]
	public System.Nullable<int> periodo
	{
		get
		{
			return this._periodo;
		}
		set
		{
			if ((this._periodo != value))
			{
				this.OnperiodoChanging(value);
				this.SendPropertyChanging();
				this._periodo = value;
				this.SendPropertyChanged("periodo");
				this.OnperiodoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_membro", DbType="TinyInt")]
	public System.Nullable<byte> membro
	{
		get
		{
			return this._membro;
		}
		set
		{
			if ((this._membro != value))
			{
				this.OnmembroChanging(value);
				this.SendPropertyChanging();
				this._membro = value;
				this.SendPropertyChanged("membro");
				this.OnmembroChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pagamento", DbType="TinyInt")]
	public System.Nullable<byte> pagamento
	{
		get
		{
			return this._pagamento;
		}
		set
		{
			if ((this._pagamento != value))
			{
				this.OnpagamentoChanging(value);
				this.SendPropertyChanging();
				this._pagamento = value;
				this.SendPropertyChanged("pagamento");
				this.OnpagamentoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_season_id", DbType="Int")]
	public System.Nullable<int> season_id
	{
		get
		{
			return this._season_id;
		}
		set
		{
			if ((this._season_id != value))
			{
				this.Onseason_idChanging(value);
				this.SendPropertyChanging();
				this._season_id = value;
				this.SendPropertyChanged("season_id");
				this.Onseason_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_horas_total", DbType="VarChar(50)")]
	public string horas_total
	{
		get
		{
			return this._horas_total;
		}
		set
		{
			if ((this._horas_total != value))
			{
				this.Onhoras_totalChanging(value);
				this.SendPropertyChanging();
				this._horas_total = value;
				this.SendPropertyChanged("horas_total");
				this.Onhoras_totalChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
