#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventControlSystem
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="the_ecs")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb_login(tb_login instance);
    partial void Updatetb_login(tb_login instance);
    partial void Deletetb_login(tb_login instance);
    partial void Inserttb_user(tb_user instance);
    partial void Updatetb_user(tb_user instance);
    partial void Deletetb_user(tb_user instance);
    partial void Inserttb_season(tb_season instance);
    partial void Updatetb_season(tb_season instance);
    partial void Deletetb_season(tb_season instance);
    partial void Inserttb_log_login(tb_log_login instance);
    partial void Updatetb_log_login(tb_log_login instance);
    partial void Deletetb_log_login(tb_log_login instance);
    partial void Inserttb_control(tb_control instance);
    partial void Updatetb_control(tb_control instance);
    partial void Deletetb_control(tb_control instance);
    partial void Inserttb_event(tb_event instance);
    partial void Updatetb_event(tb_event instance);
    partial void Deletetb_event(tb_event instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::EventControlSystem.Properties.Settings.Default.the_ecsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_login> tb_logins
		{
			get
			{
				return this.GetTable<tb_login>();
			}
		}
		
		public System.Data.Linq.Table<tb_user> tb_users
		{
			get
			{
				return this.GetTable<tb_user>();
			}
		}
		
		public System.Data.Linq.Table<tb_season> tb_seasons
		{
			get
			{
				return this.GetTable<tb_season>();
			}
		}
		
		public System.Data.Linq.Table<tb_log_login> tb_log_logins
		{
			get
			{
				return this.GetTable<tb_log_login>();
			}
		}
		
		public System.Data.Linq.Table<tb_control> tb_controls
		{
			get
			{
				return this.GetTable<tb_control>();
			}
		}
		
		public System.Data.Linq.Table<tb_event> tb_events
		{
			get
			{
				return this.GetTable<tb_event>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_login")]
	public partial class tb_login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nome;
		
		private string _Login;
		
		private string _Senha;
		
		private System.Nullable<byte> _UserStatus;
		
		private System.Nullable<System.DateTime> _UlitmoAcesso;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnLoginChanging(string value);
    partial void OnLoginChanged();
    partial void OnSenhaChanging(string value);
    partial void OnSenhaChanged();
    partial void OnUserStatusChanging(System.Nullable<byte> value);
    partial void OnUserStatusChanged();
    partial void OnUlitmoAcessoChanging(System.Nullable<System.DateTime> value);
    partial void OnUlitmoAcessoChanged();
    #endregion
		
		public tb_login()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="VarChar(20)")]
		public string Login
		{
			get
			{
				return this._Login;
			}
			set
			{
				if ((this._Login != value))
				{
					this.OnLoginChanging(value);
					this.SendPropertyChanging();
					this._Login = value;
					this.SendPropertyChanged("Login");
					this.OnLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Senha", DbType="VarChar(10)")]
		public string Senha
		{
			get
			{
				return this._Senha;
			}
			set
			{
				if ((this._Senha != value))
				{
					this.OnSenhaChanging(value);
					this.SendPropertyChanging();
					this._Senha = value;
					this.SendPropertyChanged("Senha");
					this.OnSenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserStatus", DbType="TinyInt")]
		public System.Nullable<byte> UserStatus
		{
			get
			{
				return this._UserStatus;
			}
			set
			{
				if ((this._UserStatus != value))
				{
					this.OnUserStatusChanging(value);
					this.SendPropertyChanging();
					this._UserStatus = value;
					this.SendPropertyChanged("UserStatus");
					this.OnUserStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UlitmoAcesso", DbType="DateTime")]
		public System.Nullable<System.DateTime> UlitmoAcesso
		{
			get
			{
				return this._UlitmoAcesso;
			}
			set
			{
				if ((this._UlitmoAcesso != value))
				{
					this.OnUlitmoAcessoChanging(value);
					this.SendPropertyChanging();
					this._UlitmoAcesso = value;
					this.SendPropertyChanged("UlitmoAcesso");
					this.OnUlitmoAcessoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_users")]
	public partial class tb_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nome;
		
		private string _rg;
		
		private string _telefone;
		
		private string _celular;
		
		private string _curso;
		
		private string _email;
		
		private string _ensino;
		
		private string _periodo;
		
		private System.Nullable<byte> _membro;
		
		private System.Nullable<byte> _pagamento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnrgChanging(string value);
    partial void OnrgChanged();
    partial void OntelefoneChanging(string value);
    partial void OntelefoneChanged();
    partial void OncelularChanging(string value);
    partial void OncelularChanged();
    partial void OncursoChanging(string value);
    partial void OncursoChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnensinoChanging(string value);
    partial void OnensinoChanged();
    partial void OnperiodoChanging(string value);
    partial void OnperiodoChanged();
    partial void OnmembroChanging(System.Nullable<byte> value);
    partial void OnmembroChanged();
    partial void OnpagamentoChanging(System.Nullable<byte> value);
    partial void OnpagamentoChanged();
    #endregion
		
		public tb_user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(50)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rg", DbType="VarChar(20)")]
		public string rg
		{
			get
			{
				return this._rg;
			}
			set
			{
				if ((this._rg != value))
				{
					this.OnrgChanging(value);
					this.SendPropertyChanging();
					this._rg = value;
					this.SendPropertyChanged("rg");
					this.OnrgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefone", DbType="VarChar(20)")]
		public string telefone
		{
			get
			{
				return this._telefone;
			}
			set
			{
				if ((this._telefone != value))
				{
					this.OntelefoneChanging(value);
					this.SendPropertyChanging();
					this._telefone = value;
					this.SendPropertyChanged("telefone");
					this.OntelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="VarChar(20)")]
		public string celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this.OncelularChanging(value);
					this.SendPropertyChanging();
					this._celular = value;
					this.SendPropertyChanged("celular");
					this.OncelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curso", DbType="VarChar(45)")]
		public string curso
		{
			get
			{
				return this._curso;
			}
			set
			{
				if ((this._curso != value))
				{
					this.OncursoChanging(value);
					this.SendPropertyChanging();
					this._curso = value;
					this.SendPropertyChanged("curso");
					this.OncursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ensino", DbType="VarChar(45)")]
		public string ensino
		{
			get
			{
				return this._ensino;
			}
			set
			{
				if ((this._ensino != value))
				{
					this.OnensinoChanging(value);
					this.SendPropertyChanging();
					this._ensino = value;
					this.SendPropertyChanged("ensino");
					this.OnensinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_periodo", DbType="VarChar(50)")]
		public string periodo
		{
			get
			{
				return this._periodo;
			}
			set
			{
				if ((this._periodo != value))
				{
					this.OnperiodoChanging(value);
					this.SendPropertyChanging();
					this._periodo = value;
					this.SendPropertyChanged("periodo");
					this.OnperiodoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_membro", DbType="TinyInt")]
		public System.Nullable<byte> membro
		{
			get
			{
				return this._membro;
			}
			set
			{
				if ((this._membro != value))
				{
					this.OnmembroChanging(value);
					this.SendPropertyChanging();
					this._membro = value;
					this.SendPropertyChanged("membro");
					this.OnmembroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pagamento", DbType="TinyInt")]
		public System.Nullable<byte> pagamento
		{
			get
			{
				return this._pagamento;
			}
			set
			{
				if ((this._pagamento != value))
				{
					this.OnpagamentoChanging(value);
					this.SendPropertyChanging();
					this._pagamento = value;
					this.SendPropertyChanged("pagamento");
					this.OnpagamentoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_season")]
	public partial class tb_season : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nome;
		
		private string _Data;
		
		private string _Certificado;
		
		private System.Nullable<byte> _Deletado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnDataChanging(string value);
    partial void OnDataChanged();
    partial void OnCertificadoChanging(string value);
    partial void OnCertificadoChanged();
    partial void OnDeletadoChanging(System.Nullable<byte> value);
    partial void OnDeletadoChanged();
    #endregion
		
		public tb_season()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="VarChar(50)")]
		public string Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Certificado", DbType="VarChar(15)")]
		public string Certificado
		{
			get
			{
				return this._Certificado;
			}
			set
			{
				if ((this._Certificado != value))
				{
					this.OnCertificadoChanging(value);
					this.SendPropertyChanging();
					this._Certificado = value;
					this.SendPropertyChanged("Certificado");
					this.OnCertificadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deletado", DbType="TinyInt")]
		public System.Nullable<byte> Deletado
		{
			get
			{
				return this._Deletado;
			}
			set
			{
				if ((this._Deletado != value))
				{
					this.OnDeletadoChanging(value);
					this.SendPropertyChanging();
					this._Deletado = value;
					this.SendPropertyChanged("Deletado");
					this.OnDeletadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_log_login")]
	public partial class tb_log_login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _LoginID;
		
		private string _Nome;
		
		private string _Evento;
		
		private System.Nullable<System.DateTime> _Tempo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLoginIDChanging(System.Nullable<int> value);
    partial void OnLoginIDChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnEventoChanging(string value);
    partial void OnEventoChanged();
    partial void OnTempoChanging(System.Nullable<System.DateTime> value);
    partial void OnTempoChanged();
    #endregion
		
		public tb_log_login()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginID", DbType="Int")]
		public System.Nullable<int> LoginID
		{
			get
			{
				return this._LoginID;
			}
			set
			{
				if ((this._LoginID != value))
				{
					this.OnLoginIDChanging(value);
					this.SendPropertyChanging();
					this._LoginID = value;
					this.SendPropertyChanged("LoginID");
					this.OnLoginIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Evento", DbType="VarChar(20)")]
		public string Evento
		{
			get
			{
				return this._Evento;
			}
			set
			{
				if ((this._Evento != value))
				{
					this.OnEventoChanging(value);
					this.SendPropertyChanging();
					this._Evento = value;
					this.SendPropertyChanged("Evento");
					this.OnEventoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tempo", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tempo
		{
			get
			{
				return this._Tempo;
			}
			set
			{
				if ((this._Tempo != value))
				{
					this.OnTempoChanging(value);
					this.SendPropertyChanging();
					this._Tempo = value;
					this.SendPropertyChanged("Tempo");
					this.OnTempoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_control")]
	public partial class tb_control : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _event_id;
		
		private System.Nullable<int> _user_id;
		
		private string _nome;
		
		private System.Nullable<System.DateTime> _entrada;
		
		private System.Nullable<System.DateTime> _saida;
		
		private string _horas;
		
		private System.Nullable<int> _checkin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onevent_idChanging(System.Nullable<int> value);
    partial void Onevent_idChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnentradaChanging(System.Nullable<System.DateTime> value);
    partial void OnentradaChanged();
    partial void OnsaidaChanging(System.Nullable<System.DateTime> value);
    partial void OnsaidaChanged();
    partial void OnhorasChanging(string value);
    partial void OnhorasChanged();
    partial void OncheckinChanging(System.Nullable<int> value);
    partial void OncheckinChanged();
    #endregion
		
		public tb_control()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_id", DbType="Int")]
		public System.Nullable<int> event_id
		{
			get
			{
				return this._event_id;
			}
			set
			{
				if ((this._event_id != value))
				{
					this.Onevent_idChanging(value);
					this.SendPropertyChanging();
					this._event_id = value;
					this.SendPropertyChanged("event_id");
					this.Onevent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
		public System.Nullable<int> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(255)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entrada", DbType="DateTime")]
		public System.Nullable<System.DateTime> entrada
		{
			get
			{
				return this._entrada;
			}
			set
			{
				if ((this._entrada != value))
				{
					this.OnentradaChanging(value);
					this.SendPropertyChanging();
					this._entrada = value;
					this.SendPropertyChanged("entrada");
					this.OnentradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saida", DbType="DateTime")]
		public System.Nullable<System.DateTime> saida
		{
			get
			{
				return this._saida;
			}
			set
			{
				if ((this._saida != value))
				{
					this.OnsaidaChanging(value);
					this.SendPropertyChanging();
					this._saida = value;
					this.SendPropertyChanged("saida");
					this.OnsaidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_horas", DbType="VarChar(50)")]
		public string horas
		{
			get
			{
				return this._horas;
			}
			set
			{
				if ((this._horas != value))
				{
					this.OnhorasChanging(value);
					this.SendPropertyChanging();
					this._horas = value;
					this.SendPropertyChanged("horas");
					this.OnhorasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkin", DbType="Int")]
		public System.Nullable<int> checkin
		{
			get
			{
				return this._checkin;
			}
			set
			{
				if ((this._checkin != value))
				{
					this.OncheckinChanging(value);
					this.SendPropertyChanging();
					this._checkin = value;
					this.SendPropertyChanged("checkin");
					this.OncheckinChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_event")]
	public partial class tb_event : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nome;
		
		private System.Nullable<System.DateTime> _entrada;
		
		private System.Nullable<System.DateTime> _saida;
		
		private string _horas;
		
		private System.Nullable<int> _season_id;
		
		private System.Nullable<byte> _deletado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnentradaChanging(System.Nullable<System.DateTime> value);
    partial void OnentradaChanged();
    partial void OnsaidaChanging(System.Nullable<System.DateTime> value);
    partial void OnsaidaChanged();
    partial void OnhorasChanging(string value);
    partial void OnhorasChanged();
    partial void Onseason_idChanging(System.Nullable<int> value);
    partial void Onseason_idChanged();
    partial void OndeletadoChanging(System.Nullable<byte> value);
    partial void OndeletadoChanged();
    #endregion
		
		public tb_event()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(50)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entrada", DbType="DateTime")]
		public System.Nullable<System.DateTime> entrada
		{
			get
			{
				return this._entrada;
			}
			set
			{
				if ((this._entrada != value))
				{
					this.OnentradaChanging(value);
					this.SendPropertyChanging();
					this._entrada = value;
					this.SendPropertyChanged("entrada");
					this.OnentradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saida", DbType="DateTime")]
		public System.Nullable<System.DateTime> saida
		{
			get
			{
				return this._saida;
			}
			set
			{
				if ((this._saida != value))
				{
					this.OnsaidaChanging(value);
					this.SendPropertyChanging();
					this._saida = value;
					this.SendPropertyChanged("saida");
					this.OnsaidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_horas", DbType="VarChar(50)")]
		public string horas
		{
			get
			{
				return this._horas;
			}
			set
			{
				if ((this._horas != value))
				{
					this.OnhorasChanging(value);
					this.SendPropertyChanging();
					this._horas = value;
					this.SendPropertyChanged("horas");
					this.OnhorasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_season_id", DbType="Int")]
		public System.Nullable<int> season_id
		{
			get
			{
				return this._season_id;
			}
			set
			{
				if ((this._season_id != value))
				{
					this.Onseason_idChanging(value);
					this.SendPropertyChanging();
					this._season_id = value;
					this.SendPropertyChanged("season_id");
					this.Onseason_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deletado", DbType="TinyInt")]
		public System.Nullable<byte> deletado
		{
			get
			{
				return this._deletado;
			}
			set
			{
				if ((this._deletado != value))
				{
					this.OndeletadoChanging(value);
					this.SendPropertyChanging();
					this._deletado = value;
					this.SendPropertyChanged("deletado");
					this.OndeletadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
